version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php8.3-node24
    container_name: zakiah-app
    env_file: .env
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www
      - /var/www/node_modules
      - /var/www/vendor
      - /var/www/bootstrap/ssr
      - /var/www/public/build
      # Khusus Wayfinder:
      - /var/www/resources/js/wayfinder
      - /var/www/resources/js/actions
      - /var/www/resources/js/routes
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - zakiah-network

networks:
  zakiah-network:
    driver: bridge
