services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    # Baris di bawah ini sangat penting:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
